### ISSUE TITLE
many to many .populate error

### ISSUE THREAD

**Issue by crobinson42** [balderdashy/waterline-docs#33]
I have one-to-many attribute and also a many-to-many attribute - when using .populate() I have resolved that an error is thrown when you attempt to .populate() the one-to-many association BEFORE the many-to-many association. 

It seems to work if I .populate() many-to-many before .populate() one-to-many.

User.findOne("548e30d118cdb0c41553ccbd")
  .populate('company')
  .populate('regions')
  .exec( function userFound(err, user) {
	console.log('User Authenticated.');
	console.dir(user);
  });

----- throws err -------

/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;      
              ^
TypeError: Cannot read property 'where' of undefined
    at _afterFetchingJunctorRecords (/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/waterline-cursor/cursor/populateBuffers.js:131:35)
    at /Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/lib/collection.js:103:5
    at /Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:163:16
    at commandHandler (/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:709:16)
    at /Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/db.js:1846:9
    at Server.Base._callHandler (/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at MongoReply.parseBody (/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/coryrobinson/projects/thermsv3/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at emit (events.js:95:17)
|___mmBooyaH!___| ~/projects/thermsv3

**Comment by devinivy** [comment]
Thanks for the heads-up.  Do you mind reposting this in the [waterline repo](https://github.com/balderdashy/waterline/issues) repo so it gets some attention?
